---
title: "ADS 500B Project: Cleaning and Initial Modeling"
author: "Madeline Chang"
date: "2024-03-01"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(dplyr)
library(tidyverse) 
library(tidymodels)
library(mosaic) 
library(cluster)  
library(factoextra)
library(lubridate)
```

```{r}
housing_sales<- read.csv("~/ADS/ADS 500B/Datasets/house_sales.csv") #reading in data
```

```{r}
housing_clean<- housing_sales %>% #will be updated as we decide what to do with NAs
  filter(price != is.na(price))

housing_clean[2] <- housing_clean[2] %>% 
  mutate(date = as.character(date)) %>%
  mutate(date = str_remove(date, "T000000")) %>%
  mutate(date = ymd(date)) #fixing the date with lubridate
```

```{r}
housing_clean[15871,4]<- 3

housing_clean <- housing_clean %>%
  mutate(sqft_living = ifelse(is.na(sqft_living), sqft_living15, sqft_living), #replaces NA living sqft with the mean of the nearest 15 neighbors' living sqft measurement
         sqft_lot = ifelse(is.na(sqft_lot), sqft_lot15, sqft_lot), #replaces NA lot sqft with the mean of the nearest 15 neighbors' lot sqft measurement
         bedrooms = case_when(
           is.na(bedrooms) & sqft_living < 1000 ~ 1,
           is.na(bedrooms) & sqft_living < 1500 ~ 2,
           is.na(bedrooms) & sqft_living < 2000 ~ 3,
           is.na(bedrooms) & sqft_living < 2600 ~ 4,
           is.na(bedrooms) & sqft_living < 2900 ~ 5,
           is.na(bedrooms) & sqft_living <= 3000 ~ 6,
           is.na(bedrooms) & sqft_living > 3000 ~ 7,
           .default = bedrooms
         ), #replaces NAs with approximations from the 500B_project_clean.RMD
         bathrooms = case_when(
           is.na(bathrooms) & sqft_living < 1000 ~ 1,
           is.na(bathrooms) & sqft_living < 1500 ~ 2,
           is.na(bathrooms) & sqft_living < 3000 ~ 3,
           is.na(bathrooms) & sqft_living < 4000 ~ 4,
           is.na(bathrooms) & sqft_living >= 4000 ~ 5,
           .default = bathrooms
         ), #replaces NAs with approximations from the 500B_project_clean.RMD
         zipcode=as.factor(zipcode),  #makes zipcode a factor
         condition_f = as.factor(condition),
         waterfront_f = as.factor(waterfront),
         view_f = as.factor(view),
         grade_f = as.factor(grade)) %>%
  filter(bedrooms != 0) #removes houses with zero bedrooms

colSums(is.na(housing_clean))
```

```{r}
ggplot(data = housing_clean, aes(x=yr_built, y=price)) +
  geom_point() +
  geom_smooth(method = "lm") # perhaps don't use this?
```

```{r}
ggplot(data = housing_clean, aes(x=sqft_living, y=price)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
ggplot(data = housing_clean, aes(x=bedrooms, y=price)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
ggplot(data = housing_clean, aes(x=bathrooms, y=price)) +
  geom_point() +
  geom_smooth(method = "lm")
```

#Splitting test and train

```{r}
set.seed(123456)
housing_split <- initial_split(housing_clean, prop=0.5)
housing_train <- training(housing_split)
housing_test <- testing(housing_split)
```


# Building models with training data 
```{r}
model0<- lm(price ~ 1, data = housing_train)
summary(model0)
```

```{r}
model1<- lm(price ~ sqft_living, data = housing_train)
summary(model1)
```

```{r}
model2<- lm(price ~ sqft_living + bedrooms + bathrooms, data = housing_train)
summary(model2)
```

```{r}
model3<- lm(price ~ sqft_living + grade, data = housing_train)
summary(model3)
```

```{r}
model4<- lm(price ~ condition + waterfront + view + grade, data = housing_train)
summary(model4)
```

```{r}
model5<- lm(price ~ condition + waterfront + view + grade + sqft_living + bedrooms, data = housing_train)
summary(model5)
```

